export const gmailSelectors = {
  messageRoot: [
    "[data-message-id]",
    "div[role=main] .ii.gt",
    "div[role=main] .a3s.aiL",
  ],
  body: [
    ".a3s.aiL",
    "[data-message-id] .a3s",
    "[data-message-id] [dir='ltr']",
    "[data-message-id] [dir='auto']",
    "[data-legacy-message-id] .a3s",
    "[data-legacy-message-id] [dir='ltr']",
    "[data-legacy-message-id] [dir='auto']",
    "[role='main'] .a3s",
    "[role='main'] [data-message-id]",
    "[role='main'] [data-legacy-message-id]",
    "[role='main'] div[dir='ltr']",
    "[role='main'] div[dir='auto']",
    "div[role=main] .ii.gt",
  ],
  subject: ["h2.hP", "[role='main'] h2", "[data-thread-perm-id]"],
  sender: ["[data-message-id] span[email]", "[data-legacy-message-id] span[email]", "[role='main'] h3 span[email]", "[role='main'] [email]", "span[email]"],
  recipient: ["[data-message-id] span[email]", "[data-legacy-message-id] span[email]", "[role='main'] span[email]"],
  warnings: ["[role=main] [role=alert]", "[role=main] .adn"],
  attachments: [
    "[role=main] [download]",
    "[role=main] [data-tooltip*='Download']",
    "[role=main] .aZo",
  ],
} as const;